#!/bin/bash
rw-r--r-- 1 root root 0 Jun  7 07:20 0-current_working_director
rw-r--r-- 1 root root 6 Jun  7 07:21 0-current_working_directory
rw-r--r-- 1 root root 74 Jun 8 01:58 1-listit
rw-r--r-- 1 root root 0 Jun  8 02:10 2-bring_me_home
rw-r--r-- 1 root root 0 Jun  8 02:12 3-listfiles
rw-r--r-- 1 root root 47 Jun 8 01:53 READM.md

